# Generated by Django 4.2.7 on 2023-11-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="category",
            field=models.CharField(default="", max_length=100),
        ),
    ]
